cc_test(
    name = "tests",
    srcs = glob(["*.cpp", "*.h"]),
    copts = ["-Idecorator_pattern/lib"],
    deps = [
        "//decorator_pattern/lib:decorator_pattern",
        "@googletest//:gtest_main",
    ],
)
